[project]
name = "flet-alchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dynaconf>=3.2.6",
    "flet[all]>=0.25.2",
    "sqlalchemy>=2.0.36",
]
