[project]
name = "flet-alchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dynaconf>=3.2.10",
    "flet[all]>=0.27.6",
    "sqlalchemy>=2.0.39",
]
